DROP TABLE IF EXISTS post;

CREATE TABLE post (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    create TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    author TEST NOT NULL,
    message TEXT NOT NULL
);